package entity;
// Generated 2017-01-06 14:50:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Obecnosci generated by hbm2java
 */
@Entity
@Table(name="obecnosci"
    ,catalog="io"
)
public class Obecnosci  implements java.io.Serializable {


     private Integer ido;
     private Lekcje lekcje;
     private Nauczyciele nauczyciele;
     private Uczniowie uczniowie;
     private boolean obecnosc;

    public Obecnosci() {
    }

    public Obecnosci(Lekcje lekcje, Nauczyciele nauczyciele, Uczniowie uczniowie, boolean obecnosc) {
       this.lekcje = lekcje;
       this.nauczyciele = nauczyciele;
       this.uczniowie = uczniowie;
       this.obecnosc = obecnosc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ido", unique=true, nullable=false)
    public Integer getIdo() {
        return this.ido;
    }
    
    public void setIdo(Integer ido) {
        this.ido = ido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Lekcje_idl", nullable=false)
    public Lekcje getLekcje() {
        return this.lekcje;
    }
    
    public void setLekcje(Lekcje lekcje) {
        this.lekcje = lekcje;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Nauczyciele_idn", nullable=false)
    public Nauczyciele getNauczyciele() {
        return this.nauczyciele;
    }
    
    public void setNauczyciele(Nauczyciele nauczyciele) {
        this.nauczyciele = nauczyciele;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Uczniowie_idu", nullable=false)
    public Uczniowie getUczniowie() {
        return this.uczniowie;
    }
    
    public void setUczniowie(Uczniowie uczniowie) {
        this.uczniowie = uczniowie;
    }

    
    @Column(name="obecnosc", nullable=false)
    public boolean isObecnosc() {
        return this.obecnosc;
    }
    
    public void setObecnosc(boolean obecnosc) {
        this.obecnosc = obecnosc;
    }




}


