package entity;
// Generated 2017-01-06 14:50:13 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Oceny generated by hbm2java
 */
@Entity
@Table(name="oceny"
    ,catalog="io"
)
public class Oceny  implements java.io.Serializable {


     private Integer idoc;
     private Nauczyciele nauczyciele;
     private Przedmioty przedmioty;
     private Uczniowie uczniowie;
     private float wartosc;
     private Date data;
     private String opis;

    public Oceny() {
    }

	
    public Oceny(Nauczyciele nauczyciele, Przedmioty przedmioty, Uczniowie uczniowie, float wartosc, Date data) {
        this.nauczyciele = nauczyciele;
        this.przedmioty = przedmioty;
        this.uczniowie = uczniowie;
        this.wartosc = wartosc;
        this.data = data;
    }
    public Oceny(Nauczyciele nauczyciele, Przedmioty przedmioty, Uczniowie uczniowie, float wartosc, Date data, String opis) {
       this.nauczyciele = nauczyciele;
       this.przedmioty = przedmioty;
       this.uczniowie = uczniowie;
       this.wartosc = wartosc;
       this.data = data;
       this.opis = opis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idoc", unique=true, nullable=false)
    public Integer getIdoc() {
        return this.idoc;
    }
    
    public void setIdoc(Integer idoc) {
        this.idoc = idoc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Nauczyciele_idn", nullable=false)
    public Nauczyciele getNauczyciele() {
        return this.nauczyciele;
    }
    
    public void setNauczyciele(Nauczyciele nauczyciele) {
        this.nauczyciele = nauczyciele;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Przedmioty_idprz", nullable=false)
    public Przedmioty getPrzedmioty() {
        return this.przedmioty;
    }
    
    public void setPrzedmioty(Przedmioty przedmioty) {
        this.przedmioty = przedmioty;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Uczniowie_idu", nullable=false)
    public Uczniowie getUczniowie() {
        return this.uczniowie;
    }
    
    public void setUczniowie(Uczniowie uczniowie) {
        this.uczniowie = uczniowie;
    }

    
    @Column(name="Wartosc", nullable=false, precision=12, scale=0)
    public float getWartosc() {
        return this.wartosc;
    }
    
    public void setWartosc(float wartosc) {
        this.wartosc = wartosc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Data", nullable=false, length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="Opis", length=45)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


