package entity;
// Generated 2017-01-06 14:50:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plan generated by hbm2java
 */
@Entity
@Table(name="plan"
    ,catalog="io"
)
public class Plan  implements java.io.Serializable {


     private Integer idp;
     private Dyrektorzy dyrektorzy;
     private String dzien;
     private String godzina;
     private String lekcja;
     private Set<Lekcje> lekcjes = new HashSet<Lekcje>(0);

    public Plan() {
    }

	
    public Plan(Dyrektorzy dyrektorzy, String dzien, String lekcja) {
        this.dyrektorzy = dyrektorzy;
        this.dzien = dzien;
        this.lekcja = lekcja;
    }
    public Plan(Dyrektorzy dyrektorzy, String dzien, String godzina, String lekcja, Set<Lekcje> lekcjes) {
       this.dyrektorzy = dyrektorzy;
       this.dzien = dzien;
       this.godzina = godzina;
       this.lekcja = lekcja;
       this.lekcjes = lekcjes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idp", unique=true, nullable=false)
    public Integer getIdp() {
        return this.idp;
    }
    
    public void setIdp(Integer idp) {
        this.idp = idp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Dyrektorzy_idd", nullable=false)
    public Dyrektorzy getDyrektorzy() {
        return this.dyrektorzy;
    }
    
    public void setDyrektorzy(Dyrektorzy dyrektorzy) {
        this.dyrektorzy = dyrektorzy;
    }

    
    @Column(name="Dzien", nullable=false, length=15)
    public String getDzien() {
        return this.dzien;
    }
    
    public void setDzien(String dzien) {
        this.dzien = dzien;
    }

    
    @Column(name="Godzina", length=20)
    public String getGodzina() {
        return this.godzina;
    }
    
    public void setGodzina(String godzina) {
        this.godzina = godzina;
    }

    
    @Column(name="Lekcja", nullable=false, length=45)
    public String getLekcja() {
        return this.lekcja;
    }
    
    public void setLekcja(String lekcja) {
        this.lekcja = lekcja;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="plan")
    public Set<Lekcje> getLekcjes() {
        return this.lekcjes;
    }
    
    public void setLekcjes(Set<Lekcje> lekcjes) {
        this.lekcjes = lekcjes;
    }




}


