package entity;
// Generated 2017-01-06 14:50:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Przedmioty generated by hbm2java
 */
@Entity
@Table(name="przedmioty"
    ,catalog="io"
)
public class Przedmioty  implements java.io.Serializable {


     private Integer idprz;
     private Nauczyciele nauczyciele;
     private String nazwa;
     private Set<Lekcje> lekcjes = new HashSet<Lekcje>(0);
     private Set<Oceny> ocenies = new HashSet<Oceny>(0);

    public Przedmioty() {
    }

	
    public Przedmioty(Nauczyciele nauczyciele, String nazwa) {
        this.nauczyciele = nauczyciele;
        this.nazwa = nazwa;
    }
    public Przedmioty(Nauczyciele nauczyciele, String nazwa, Set<Lekcje> lekcjes, Set<Oceny> ocenies) {
       this.nauczyciele = nauczyciele;
       this.nazwa = nazwa;
       this.lekcjes = lekcjes;
       this.ocenies = ocenies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idprz", unique=true, nullable=false)
    public Integer getIdprz() {
        return this.idprz;
    }
    
    public void setIdprz(Integer idprz) {
        this.idprz = idprz;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Nauczyciele_idn", nullable=false)
    public Nauczyciele getNauczyciele() {
        return this.nauczyciele;
    }
    
    public void setNauczyciele(Nauczyciele nauczyciele) {
        this.nauczyciele = nauczyciele;
    }

    
    @Column(name="Nazwa", nullable=false, length=45)
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="przedmioty")
    public Set<Lekcje> getLekcjes() {
        return this.lekcjes;
    }
    
    public void setLekcjes(Set<Lekcje> lekcjes) {
        this.lekcjes = lekcjes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="przedmioty")
    public Set<Oceny> getOcenies() {
        return this.ocenies;
    }
    
    public void setOcenies(Set<Oceny> ocenies) {
        this.ocenies = ocenies;
    }




}


