package entity;
// Generated 2017-01-06 14:50:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name="sala"
    ,catalog="io"
)
public class Sala  implements java.io.Serializable {


     private Integer ids;
     private Lekcje lekcje;
     private String numer;
     private int liczbaMiejsc;

    public Sala() {
    }

    public Sala(Lekcje lekcje, String numer, int liczbaMiejsc) {
       this.lekcje = lekcje;
       this.numer = numer;
       this.liczbaMiejsc = liczbaMiejsc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ids", unique=true, nullable=false)
    public Integer getIds() {
        return this.ids;
    }
    
    public void setIds(Integer ids) {
        this.ids = ids;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Lekcje_idl", nullable=false)
    public Lekcje getLekcje() {
        return this.lekcje;
    }
    
    public void setLekcje(Lekcje lekcje) {
        this.lekcje = lekcje;
    }

    
    @Column(name="Numer", nullable=false, length=3)
    public String getNumer() {
        return this.numer;
    }
    
    public void setNumer(String numer) {
        this.numer = numer;
    }

    
    @Column(name="Liczba miejsc", nullable=false)
    public int getLiczbaMiejsc() {
        return this.liczbaMiejsc;
    }
    
    public void setLiczbaMiejsc(int liczbaMiejsc) {
        this.liczbaMiejsc = liczbaMiejsc;
    }




}


