package entity;
// Generated 2017-01-06 14:50:13 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Uwaga generated by hbm2java
 */
@Entity
@Table(name="uwaga"
    ,catalog="io"
)
public class Uwaga  implements java.io.Serializable {


     private Integer iduw;
     private Nauczyciele nauczyciele;
     private Uczniowie uczniowie;
     private String tresc;
     private Date data;
     private boolean pozytywna;

    public Uwaga() {
    }

    public Uwaga(Nauczyciele nauczyciele, Uczniowie uczniowie, String tresc, Date data, boolean pozytywna) {
       this.nauczyciele = nauczyciele;
       this.uczniowie = uczniowie;
       this.tresc = tresc;
       this.data = data;
       this.pozytywna = pozytywna;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iduw", unique=true, nullable=false)
    public Integer getIduw() {
        return this.iduw;
    }
    
    public void setIduw(Integer iduw) {
        this.iduw = iduw;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Nauczyciele_idn", nullable=false)
    public Nauczyciele getNauczyciele() {
        return this.nauczyciele;
    }
    
    public void setNauczyciele(Nauczyciele nauczyciele) {
        this.nauczyciele = nauczyciele;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Uczniowie_idu", nullable=false)
    public Uczniowie getUczniowie() {
        return this.uczniowie;
    }
    
    public void setUczniowie(Uczniowie uczniowie) {
        this.uczniowie = uczniowie;
    }

    
    @Column(name="Tresc", nullable=false, length=100)
    public String getTresc() {
        return this.tresc;
    }
    
    public void setTresc(String tresc) {
        this.tresc = tresc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Data", nullable=false, length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="Pozytywna", nullable=false)
    public boolean isPozytywna() {
        return this.pozytywna;
    }
    
    public void setPozytywna(boolean pozytywna) {
        this.pozytywna = pozytywna;
    }




}


