package entity;
// Generated 2017-01-06 14:50:13 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wydarzenie generated by hbm2java
 */
@Entity
@Table(name="wydarzenie"
    ,catalog="io"
)
public class Wydarzenie  implements java.io.Serializable {


     private Integer idWyd;
     private Nauczyciele nauczyciele;
     private String nazwa;
     private Date data;

    public Wydarzenie() {
    }

    public Wydarzenie(Nauczyciele nauczyciele, String nazwa, Date data) {
       this.nauczyciele = nauczyciele;
       this.nazwa = nazwa;
       this.data = data;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idWyd", unique=true, nullable=false)
    public Integer getIdWyd() {
        return this.idWyd;
    }
    
    public void setIdWyd(Integer idWyd) {
        this.idWyd = idWyd;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Nauczyciele_idn", nullable=false)
    public Nauczyciele getNauczyciele() {
        return this.nauczyciele;
    }
    
    public void setNauczyciele(Nauczyciele nauczyciele) {
        this.nauczyciele = nauczyciele;
    }

    
    @Column(name="Nazwa", nullable=false, length=45)
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Data", nullable=false, length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


