package model;
// Generated 2017-01-06 01:06:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dyrektorzy generated by hbm2java
 */
@Entity
@Table(name="dyrektorzy"
    ,catalog="io"
)
public class Dyrektorzy  implements java.io.Serializable {


     private Integer idd;
     private Uzytkownicy uzytkownicy;
     private Set<Plan> plans = new HashSet<Plan>(0);

    public Dyrektorzy() {
    }

	
    public Dyrektorzy(Uzytkownicy uzytkownicy) {
        this.uzytkownicy = uzytkownicy;
    }
    public Dyrektorzy(Uzytkownicy uzytkownicy, Set<Plan> plans) {
       this.uzytkownicy = uzytkownicy;
       this.plans = plans;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idd", unique=true, nullable=false)
    public Integer getIdd() {
        return this.idd;
    }
    
    public void setIdd(Integer idd) {
        this.idd = idd;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Uzytkownicy_iduz", nullable=false)
    public Uzytkownicy getUzytkownicy() {
        return this.uzytkownicy;
    }
    
    public void setUzytkownicy(Uzytkownicy uzytkownicy) {
        this.uzytkownicy = uzytkownicy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dyrektorzy")
    public Set<Plan> getPlans() {
        return this.plans;
    }
    
    public void setPlans(Set<Plan> plans) {
        this.plans = plans;
    }




}


